Update update_afl_data.yml

diff --git a/.github/workflows/update_afl_data.yml b/.github/workflows/update_afl_data.yml
--- a/.github/workflows/update_afl_data.yml
+++ b/.github/workflows/update_afl_data.yml
@@ -18,9 +18,8 @@ jobs:
     
     - name: Install system dependencies
       run: |
-        sudo apt-get install -y jq
         sudo apt-get update
-        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libgit2-dev
+        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libgit2-dev jq
 
     - name: Set up R
       uses: r-lib/actions/setup-r@v2
@@ -68,7 +67,18 @@ jobs:
           https://www.pythonanywhere.com/api/v0/user/testingafl/consoles/ \
           -d "executable=/home/testingafl/afl_ranking_system/venv/bin/python" \
           -d "working_directory=/home/testingafl/afl_ranking_system")
+        
+        echo "Raw console response:"
+        echo "$console_response"
+        
         console_id=$(echo $console_response | jq -r .id)
+        
+        if [ -z "$console_id" ]; then
+          echo "Failed to extract console ID. Exiting."
+          exit 1
+        fi
+        
+        echo "Console ID: $console_id"
         
         # Run the script
         curl -X POST \
